"""empty message

Revision ID: 6fed0faed518
Revises: None
Create Date: 2016-05-30 16:26:18.067000

"""

# revision identifiers, used by Alembic.
revision = '6fed0faed518'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('grades', 'arrange_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grades', 'arrange_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('grades', 'id')
    ### end Alembic commands ###
