"""empty message

Revision ID: aa76c4c8f3dd
Revises: None
Create Date: 2016-04-23 15:45:05.886000

"""

# revision identifiers, used by Alembic.
revision = 'aa76c4c8f3dd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selectCourse',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('arrange_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arrange_id'], ['arranges.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_table('selectCourse')
    ### end Alembic commands ###
